### ISSUE TITLE
好兄弟，找到这个项目真不容易，要能做个列表同步更新将是绝杀

### ISSUE THREAD

**Issue by zzz6839** [Plutoyer/javdb-top250#1]
RT

听我说👂👂👂谢谢你🙏🙏🙏因为有你👉👉👉温暖了四季🌈🌈🌈谢谢你🙏🙏🙏感谢有你👉👉👉世界更美丽🌏🌏🌏我要谢谢你🙏🙏🙏因为有你👉👉👉爱常在心底💃💃💃谢谢你 🙏🙏🙏感谢有你🙇♂🙇♂🙇♂把幸福传递

**Comment by wocaishiniliu** [comment]
https://github.com/qq57240/Javdb-Top250
这个兄弟一直在更新！！！
拿走不谢

**Comment by zzz6839** [comment]
> https://github.com/qq57240/Javdb-Top250 这个兄弟一直在更新！！！ 拿走不谢

谢谢你，加里奥
